"""Embedding module with pluggable backends."""

import hashlib
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Optional, Dict, Any
import numpy as np


@dataclass
class EmbeddingResult:
    """Result of an embedding operation."""
    vectors: np.ndarray
    dimension: int
    backend: str


class BaseEmbeddingBackend(ABC):
    """Abstract base class for embedding backends."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the name of this backend."""
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """Return the embedding dimension."""
        pass

    @abstractmethod
    def embed(self, texts: List[str]) -> np.ndarray:
        """Embed a list of texts into vectors.

        Args:
            texts: List of text strings to embed.

        Returns:
            Numpy array of shape (len(texts), dimension)
        """
        pass


class StubEmbeddingBackend(BaseEmbeddingBackend):
    """Deterministic stub embedding backend for testing.

    This backend generates deterministic pseudo-vectors based on
    the SHA-256 hash of the input text. The same text will always
    produce the same vector.
    """

    def __init__(self, dimension: int = 128):
        """Initialize the stub embedding backend.

        Args:
            dimension: Dimension of the output vectors.
        """
        self._dimension = dimension

    @property
    def name(self) -> str:
        return "stub"

    @property
    def dimension(self) -> int:
        return self._dimension

    def embed(self, texts: List[str]) -> np.ndarray:
        """Generate deterministic pseudo-vectors.

        The vector is generated by:
        1. Computing SHA-256 hash of each text
        2. Converting hash bytes to floats
        3. Normalizing to unit length (L2 norm)
        """
        if not texts:
            return np.zeros((0, self._dimension), dtype=np.float32)

        vectors = []
        for text in texts:
            hash_obj = hashlib.sha256(text.encode('utf-8'))
            hash_bytes = hash_obj.digest()

            vector = []
            for i in range(self._dimension):
                byte_idx = i % len(hash_bytes)
                byte_val = hash_bytes[byte_idx]
                next_byte = hash_bytes[(byte_idx + 1) % len(hash_bytes)]
                val = (byte_val * 256 + next_byte) / 65535.0
                vector.append(val * 2.0 - 1.0)

            vector_np = np.array(vector, dtype=np.float32)
            norm = np.linalg.norm(vector_np)
            if norm > 0:
                vector_np = vector_np / norm
            vectors.append(vector_np)

        return np.array(vectors, dtype=np.float32)


class OpenAIEmbeddingBackend(BaseEmbeddingBackend):
    """OpenAI embedding backend.

    Requires OPENAI_API_KEY environment variable to be set.
    """

    def __init__(self, model: str = "text-embedding-ada-002", api_key: Optional[str] = None):
        """Initialize the OpenAI embedding backend.

        Args:
            model: Name of the OpenAI embedding model.
            api_key: OpenAI API key. If None, reads from OPENAI_API_KEY env var.

        Raises:
            ImportError: If openai package is not installed.
            ValueError: If API key is not provided.
        """
        self._model = model
        self._api_key = api_key or os.getenv("OPENAI_API_KEY")

        if not self._api_key:
            raise ValueError(
                "OpenAI API key not provided. Set OPENAI_API_KEY environment variable "
                "or pass api_key parameter."
            )

        try:
            import openai
            self._client = openai.OpenAI(api_key=self._api_key)
        except ImportError:
            raise ImportError(
                "openai package not installed. Install with: pip install openai>=1.0"
            )

        self._dimension = self._get_dimension()

    @property
    def name(self) -> str:
        return "openai"

    @property
    def dimension(self) -> int:
        return self._dimension

    def _get_dimension(self) -> int:
        """Get the embedding dimension for the model."""
        dimension_map = {
            "text-embedding-ada-002": 1536,
            "text-embedding-3-small": 1536,
            "text-embedding-3-large": 3072,
        }
        return dimension_map.get(self._model, 1536)

    def embed(self, texts: List[str]) -> np.ndarray:
        """Embed texts using OpenAI API."""
        if not texts:
            return np.zeros((0, self._dimension), dtype=np.float32)

        response = self._client.embeddings.create(
            model=self._model,
            input=texts
        )

        vectors = []
        for item in response.data:
            vectors.append(np.array(item.embedding, dtype=np.float32))

        return np.array(vectors, dtype=np.float32)


def get_embedding_backend(backend: str = "stub", **kwargs) -> BaseEmbeddingBackend:
    """Get an embedding backend instance.

    Args:
        backend: Name of the backend to use ('stub' or 'openai').
        **kwargs: Additional arguments passed to the backend constructor.

    Returns:
        An instance of BaseEmbeddingBackend.

    Raises:
        ValueError: If the backend is unknown.
    """
    if backend == "stub":
        return StubEmbeddingBackend(**kwargs)
    elif backend == "openai":
        return OpenAIEmbeddingBackend(**kwargs)
    else:
        raise ValueError(f"Unknown embedding backend: {backend}")


def get_embedding_backend_from_config(config: Dict[str, Any]) -> BaseEmbeddingBackend:
    """Get embedding backend from configuration dictionary.

    Args:
        config: Configuration dict with 'backend' key and optional parameters.

    Returns:
        An instance of BaseEmbeddingBackend.
    """
    backend = config.get("backend", "stub")
    params = config.get("params", {})
    return get_embedding_backend(backend, **params)
